server:
  port: 3001
  host: 0.0.0.0

auth:
  enabled: true
  pocketbase:
    url: http://127.0.0.1:8090
    admin_email: ${POCKETBASE_ADMIN_EMAIL}
    admin_password: ${POCKETBASE_ADMIN_PASSWORD}

operations:
  background-remove:
    provider: replicate
  unblur:
    provider: replicate
  colorize:
    provider: replicate
  inpaint:
    provider: replicate
  restore:
    provider: replicate

providers:
  replicate:
    api_key: ${REPLICATE_API_KEY}
